### PR TITLE
Sorting & regroup about 'Health panel' lines.

### PR DESCRIPTION
**Pull request by Mishasama**
Sorting & regroup about 'Health panel' for new lines.
And replace all 'Tabs' with '4 spaces' to unify the style.

### CODE REVIEW

**Comment by Faalagorn** [comment]
@Mishasama I saw you left tabs in comments; is it intentional? I've been thinking about running lua linter against whole project to unify the style, though I'm not sure how TranslatoidZed which is hosted here but technically doesn't have a source code here to fix adapts to it and won't override it anyway.

**Comment by Mishasama** [comment]
> @Mishasama I saw you left tabs in comments; is it intentional? I've been thinking about running lua linter against whole project to unify the style, though I'm not sure how TranslationZed which is hosted here but technically doesn't have a source code here to fix adapts to it and won't override it anyway.

Yes, intentional, it should be easier to read on the text editor.

The TranslationZed will delete all comments and change all tabs to 4 spaces, but not sort at all. I don't use it personally. Its only use for me is to track changes.

**Comment by Faalagorn** [comment]
> > @Mishasama I saw you left tabs in comments; is it intentional? I've been thinking about running lua linter against whole project to unify the style, though I'm not sure how TranslationZed which is hosted here but technically doesn't have a source code here to fix adapts to it and won't override it anyway.
> 
> Yes, intentional, it should be easier to read on the text editor.
> 
> The TranslationZed will delete all comments and change all tabs to 4 spaces, but not sort at all. I don't use it personally. Its only use for me is to track changes.

Thanks! I don't use it either, though some future editors might use it. Would be nice if the style could somehow be unified, though we sadly don't have code for TranslationZed as I said to fix it :(

**Comment by Mishasama** [comment]
> Thanks! I don't use it either, though some future editors might use it. Would be nice if the style could somehow be unified, though we sadly don't have code for TranslationZed as I said to fix it :(

Uh... Java... Try these...
https://github.com/skylot/jadx/
https://github.com/deathmarine/Luyten
http://jd.benow.ca/

Or just ask TIS...😅

**Pull request merged**
