### PR TITLE
Fixed encode

### PR DESCRIPTION
**Pull request by Mishasama**
Fixed encode error and keep [our agreement](https://github.com/TheIndieStone/ProjectZomboidTranslations/pull/341#issuecomment-686365433) not be violated.

**Note for the other contributors:
Please respect the labor achievements of the predecessors. And make sure your contribution does not make things worse.
If you want to add your name to this, just add yours with new lines, don't modify the others lines. And be sure to save as GB2312, not others.**

### CODE REVIEW

**Comment by moonlight-pz** [comment]
image
The original file has no format errors. And the Chinese translation has been re-made. The names of former Chinese translators have also been added to the acknowledgement list. However, it is not advisable to use an official Chinese translation to get publicity, especially if you sell a paid Chinese translation.

**Comment by Mishasama** [comment]
> image
> The original file has no format errors. And the Chinese translation has been re-made. The names of former Chinese translators have also been added to the acknowledgement list. However, it is not advisable to use an official Chinese translation to get publicity, especially if you sell a paid Chinese translation.

Then please delete all our old works and rebuild them yourself. Don't have any of the same words, and make a clear statement. MANY THANKS!

**Comment by moonlight-pz** [comment]
> > image
> > The original file has no format errors. And the Chinese translation has been re-made. The names of former Chinese translators have also been added to the acknowledgement list. However, it is not advisable to use an official Chinese translation to get publicity, especially if you sell a paid Chinese translation.
> 
> Then please delete all our old works and rebuild them yourself. Don't have any of the same words, and make a clear statement. MANY THANKS!


are you kidding me? Don’t use any of the same words?Table is not called table(桌子)?thank you is not called thank you(谢谢)? One is not called one(一)? 
New Chinese translation is different from old Chinese translation. Because he comes from the English version. We have already issued a statement. 
Please stay awake. Don't make these unreasonable demands.

**Comment by Mishasama** [comment]
> are you kidding me? Don’t use any of the same words?Table is not called table(桌子)?thank you is not called thank you(谢谢)? One is not called one(一)?
> New Chinese translation is different from old Chinese translation. Because he comes from the English version. We have already issued a statement.
> Please stay awake. Don't make these unreasonable demands.

I knew you are good at changing the old translation words to something different new things.
So please keep on it and believe in yourself, you can do it.

And your statement of violation of the agreement should be in the game to ensure that it's shown to all players, not just under your groups.

**Comment by moonlight-pz** [comment]
> > are you kidding me? Don’t use any of the same words?Table is not called table(桌子)?thank you is not called thank you(谢谢)? One is not called one(一)?
> > New Chinese translation is different from old Chinese translation. Because he comes from the English version. We have already issued a statement.
> > Please stay awake. Don't make these unreasonable demands.
> 
> I knew you are good at changing the old translation words to something different new things.
> So please keep on it and believe in yourself, you can do it.
> 
> And your statement of violation of the agreement should be in the game to ensure that it's shown to all players, not just under your groups.
> Then you should delete all the old team member's names to tell ppl the new translation is not from us, and leave all the 'honor' to your team.

I just translated according to the English version. The translation standard is English-Chinese dictionary and English meaning. Will not add or delete meanings without authorization like you. And we also let players participate in Chinese translation. Correct the wrong translation in time.
Please note that the Chinese language is not yours. The English-Chinese translation should be accurate and elegant. The wording is also changed for accuracy and elegance. And every time we change the wording, we will discuss it
If your name does not want to appear in the list, we will delete it. But I have not received other requests to delete. If they request, we will follow suit. Your name appears in the list, just to show respect

**Comment by nsKpz** [comment]
Updated the credits with the links, as before. Added the new names from the last commit. 
https://github.com/TheIndieStone/ProjectZomboidTranslations/commit/03225df597a3065611aadad4855dc584afc1ba98

**Pull request closed without merging**
