### PR TITLE
Encodings

### LINKED ISSUE #155: encoding issue
I'm trying to update russian translation to the latest PZ version but I run into a problem which I can't solve (I remember same issue was here year ago). So what issue is.
Currently all russian .txt files use windows 1251 encoding which can be read by game (text displayed normally). But for some reason files on github are broken (hieroglyphs all the way). I thought well maybe github can't display windows 1251 files but for some reason SOME files displayed normally and some aren't.

For comparison:
1. https://github.com/TheIndieStone/ProjectZomboidTranslations/blob/master/RU/Challenge_RU.txt this file uses windows 1251 encoding and displayed correctly
2. https://github.com/TheIndieStone/ProjectZomboidTranslations/blob/master/RU/ContextMenu_RU.txt this file uses same windows 1251 encoding but as you can see some crazy characters appear here.

So question is why this happens? How do I fix it? If you download these files they displayed normally but not in repository. Also, UTF-8 works for github but game won't display them although english files encoded in UTF-8 are displayed correctly. There are no problems in displaying russian symbols in minecraft for example in UTF-8, seems like zomboid needs different encoding for each language.

### PR DESCRIPTION
**Pull request by Tiax**
Attempt to resolve #155

### CODE REVIEW

**Comment by Faalagorn** [comment]
You beat me to it, but at least I got the time to clean up and properly set up my local repo :). I'll test it in a minute

**Comment by Faalagorn** [comment]
It seems to work just fine for me: 
screenshot_2021-01-16-151229

**Comment by nsKpz** [comment]
Fantastic, thank you

**Review by Mishasama — COMMENTED** [review]
Remind: The CN/credits.txt is using GB2312... not the UTF-8...😂

**Comment by nsKpz** [comment]
@Mishasama This is a change to make them show up correctly on Github. The encoding of the game files will remain.

**Comment by Tiax** [comment]
Is that file read by the game expecting that encoding? I assumed that's just an info file, so they're all exported as unicode, right now.

This was the state before any encoding changes:
```$ git log -1
commit 26ec9cea9299f33d32f0dfae8dd0960313882387 (HEAD)
Author: nsKpz <martinnasko@gmail.com>
Date:   Thu Jan 14 15:28:29 2021 +0100

    Update credits.txt

    Removed links until all references to the QQ group are removed from said sites.

$ file -i */credits.txt
AF/credits.txt:   text/plain; charset=us-ascii
AR/credits.txt:   text/plain; charset=us-ascii
CH/credits.txt:   text/plain; charset=us-ascii
CN/credits.txt:   text/plain; charset=unknown-8bit
CS/credits.txt:   text/plain; charset=us-ascii
DA/credits.txt:   text/plain; charset=us-ascii
DE/credits.txt:   text/plain; charset=us-ascii
EE/credits.txt:   inode/x-empty; charset=binary
ES/credits.txt:   text/plain; charset=us-ascii
FR/credits.txt:   text/plain; charset=us-ascii
HU/credits.txt:   text/plain; charset=us-ascii
IT/credits.txt:   text/plain; charset=us-ascii
JP/credits.txt:   text/plain; charset=us-ascii
KO/credits.txt:   text/plain; charset=us-ascii
NL/credits.txt:   text/plain; charset=us-ascii
NO/credits.txt:   text/plain; charset=us-ascii
PL/credits.txt:   text/plain; charset=us-ascii
PT/credits.txt:   text/plain; charset=us-ascii
PTBR/credits.txt: text/plain; charset=us-ascii
RU/credits.txt:   text/plain; charset=us-ascii
TH/credits.txt:   text/plain; charset=us-ascii
TR/credits.txt:   text/plain; charset=us-ascii
UA/credits.txt:   text/plain; charset=us-ascii```

**Comment by Mishasama** [comment]
> @Mishasama This is a change to make them show up correctly on Github. The encoding of the game files will remain. :)

I know what is this... But I don't know how to add the rule for this file.😓

Maybe like this?
```suggestion
CN/credits.txt text working-tree-encoding=gb2312 encoding=utf-8
```

**Comment by Tiax** [comment]
OK sooooo: the game reads the credits.txt to show it under the language selection (zombie.Lua.LuaManager.GlobalObject#getTranslatorCredits(Language)).

It currently does not specify an encoding for doing that, so it defaults to the system encoding (WIN1252 in my case, German windows). That means: it doesn't really matter what we encode the file in: it will always be broken on one system or another, unless that is changed.

**Pull request merged**
