### PR TITLE
41.67 CN

### PR DESCRIPTION
**Pull request by moonlight-pz**

### CODE REVIEW

**Comment by nsKpz** [comment]
This currently conflicts with CN/Recorded_Media_CN.txt

Can you take another look on what should be kept?

**Comment by moonlight-pz** [comment]
> This currently conflicts with CN/Recorded_Media_CN.txt
> 
> Can you take another look on what should be kept?

We'll check, Don't merge until we let you know,Thank you!

**Comment by moonlight-pz** [comment]
@nsKpz 
We've checked it out, please merge it, thanks!
have a good day

**Comment by nsKpz** [comment]
<3

**Pull request merged**
