### PR TITLE
Change Traditional Chinese charset to utf-8

### PR DESCRIPTION
**Pull request by nickexe**
Change Traditional Chinese charset and text to utf-8

### CODE REVIEW

**Comment by mrazgrass** [comment]
It's the CodeBay.in Nick! Happy to see you here. I've always been a fan of your works.

Would a change like this work? I tried this before and it seemed fine in offline test - but I don't know if we get to do things like this.

I think it's best if we discuss it on the official Discord channel with the staff/manager first.

**Comment by mrazgrass** [comment]
I'm guessing this was done in an attempt to fix the current Recorded_Media_CH problem caused by the file being in UTF-8 instead of Big5, but that specific issue has now been fixed here, only not yet published to Steam.

But I might be wrong, either way I hope you can join the discussion on the official Discord channel!

**Review by mrazgrass — APPROVED** [review]
I've tested these offline and they worked. I hope we change our charset to UTF-8 as well.

**Comment by mrazgrass** [comment]
It only works after the .gitattribute change on GitHub, which would change the encoding of every files in CH to UTF-8.

**Comment by nsKpz** [comment]
The gitattribute changes on github have no effect on the game.

**Comment by nsKpz** [comment]
Ah my bad. Github Desktop didn't change the encoding when I switched to this branch, had to delete and refetch.

**Pull request merged**
