### PR TITLE
Add some missing Ukrainian translations

### PR DESCRIPTION
**Pull request by Volosh1n**
It's all from my game expirience with Ukrainian language selected in settings

### CODE REVIEW

**Comment by valentk** [comment]
You may be interested #965

**Comment by Volosh1n** [comment]
@valentk want a review or what?

**Comment by valentk** [comment]
Well, if you want to, I'd be happy. But just saying that there already is a big PR for translations, if you want to cooperate.

**Comment by Volosh1n** [comment]
@valentk yes, since your PR is a large amount of work, I think it's better to just copy any of my translations that you may miss and then I can close my PR to avoid confusing of reviewers from IndieStone. Feel free to ping me here when missing translations will be in your PR already (if there are any of such, ofc). The only thing I would insist: stale could be "несвіже", since fresh==свіже 😄  But it's up to you, I don't mind

**Comment by valentk** [comment]
@Volosh1n Yeah, there is a lots of changes  since Gorbach started  this. If you want to help, you can join his Discord. You can find it on the mod page of translation (type UA in steam search). We kinda started to discuss translation things there. Some things are just hard to translate and keep similar size tbh. and there are still 5k lines to translate with recorded media

**Comment by Volosh1n** [comment]
Not needed, since most of it was addressed in #965

**Pull request closed without merging**
