### PR TITLE
Build 41.50

### PR DESCRIPTION
**Pull request by artdekdok**
Update for Build 41.50

### CODE REVIEW

**Comment by artdekdok** [comment]
New fonts for Thai language, please include this to the game.
[PZTH_Fonts.zip](https://github.com/TheIndieStone/ProjectZomboidTranslations/files/6331841/PZTH_Fonts.zip)

**Comment by nsKpz** [comment]
Can you please provide more information about the fonts used in this? 
Since we're a commercial product, we can't just use any font, since they might not be for commercial use.

Screenshots of the differences would also be handy and speed up the process.

**Comment by artdekdok** [comment]
I create new font for folder 1x, 2x, 3x and 4x with this font.
https://fontesk.com/boon-typeface/
Free for commercial use

and create handwritten font with this font (no default handwritten font for Thai language).
https://fonts.google.com/specimen/Sriracha?subset=thai#standard-styles

and here screenshots of default and new font (1x).

1x-1

1x-2

default-1

default-2

handwritten


[New.TH.Fonts.zip](https://github.com/TheIndieStone/ProjectZomboidTranslations/files/6387316/New.TH.Fonts.zip)

**Comment by nsKpz** [comment]
Reopening.

@artdekdok Could you modify the fonts so they don't overwrite the Original by renaming them e.g. handwritteThai, zomboidLargeThai, and so on?

**Comment by artdekdok** [comment]
> 
> 
> Reopening.
> 
> @artdekdok Could you modify the fonts so they don't overwrite the Original by renaming them e.g. handwritteThai, zomboidLargeThai, and so on?

Ok, here renamed and modified .fnt 
[New.TH.Fonts2.zip](https://github.com/TheIndieStone/ProjectZomboidTranslations/files/6793847/New.TH.Fonts2.zip)

but how does it work? because i didn't change anything in fonts.txt and game can't use new fonts if not match in fonts.txt

**Comment by nsKpz** [comment]
They'd have to be renamed accordingly in fonts.txt too :)

**Pull request closed without merging**
