### PR TITLE
Brazilian Portuguese translation overhaul

### PR DESCRIPTION
**Pull request by R4to0**
This is an effort by a group of translators to bring a high quality Brazilian Portuguese translation to the game. We are overhauling the entire translation from scratch to ensure everything fits well in the game with a thorough inspection and revision line by line.

This is a work in progress as the project is still half done. Newcomers are welcome to contribute to this project by just contacting me or @Welenkens and we'll invite to our Discord server where everything is happening. English and Portuguese proficiency highly recommended.

Please contact us before working on anything outside this so there's no risky overwriting new works done directly into upstream repository.

### CODE REVIEW

**Comment by R4to0** [comment]
Noticed that in one of the commits there are 'changes' for the Spanish translation but I'm sure I didn't touched these. These might came from one of the upstream syncs I've done locally as I've been getting lots of encoding conflict issues locally. I will see if I can get those away from this PR before finishing.

**Comment by radiusgreenhill** [comment]
> Noticed that in one of the commits there are 'changes' for the Spanish translation but I'm sure I didn't touched these. These might came from one of the upstream syncs I've done locally as I've been getting lots of encoding conflict issues locally. I will see if I can get those away from this PR before finishing.

I have no idea how those Spanish files come up in my changes either. I have to delete my local project files and pull them back as new.

If anyone knows what caused this, please elaborate.

**Comment by R4to0** [comment]
> I have no idea how those Spanish files come up in my changes either. I have to delete my local project files and pull them back as new.
> 
> If anyone knows what caused this, please elaborate.

When cloning the repository locally you get a bunch of encoding conversion errors making Git client threats as modified because they don't have the encoding set it is expecting as in .gitattributes. This might be why some of us have them as 'modified' locally. Only Spanish and Chinese give me those issues and I have to move my edited files out, hard reset the working dir, sync with upstream and move my local changes back. It is annoying but not much can be done.

**Comment by nsKpz** [comment]
A reminder that a lot of this would be really useful to have for the BR translation, so you can submit it for merging even if it is not 100% done and treat it as an ongoing thing like all other languages as well.

**Comment by R4to0** [comment]
> A reminder that a lot of this would be really useful to have for the BR translation, so you can submit it for merging even if it is not 100% done and treat it as an ongoing thing like all other languages as well.

Would like to do that but since we took the "redo everything" route we started from English as a base and didn't have done the critical stuff (like the menus) which were done before and people would be pissed off with the game 😬.

Not wanting to prevent anything coming to upstream though.

**Comment by nsKpz** [comment]
Alrighty, just thought I'd note :)

<3

**Pull request merged**
