### PR TITLE
[FR] Fix 2 typos in survival guide

### PR DESCRIPTION
**Pull request by morphalus**
Hi,

Just a little pull request to fix a typo

### CODE REVIEW

**Comment by Xianahh** [comment]
Thanks for this typo, didn't noticed it @morphalus

**Comment by morphalus** [comment]
You're welcome @Xianahh :)

**Comment by morphalus** [comment]
I just noticed another one mistake in the same line

`meilleur source de lumière` -> `meilleure source de lumière`

I renamed the PR name

**Comment by Xianahh** [comment]
What do you mean by "renamed the PR name ?"

**Pull request merged**
