### PR TITLE
Update 41.65 CN

### PR DESCRIPTION
**Pull request by moonlight-pz**

### CODE REVIEW

**Comment by mrazgrass** [comment]
You'd want to make sure if the game supports full-form punctuation marks such as "：" or "。".

I made the same mistake by including any sort of full-form symbols in Traditional Chinese translation, the game wouldn't display them. I'm not sure if the same problem occurs in Simplified Chinese, though. Just a gentle reminder.

**Comment by mrazgrass** [comment]
Never mind the last comment, it'd seems like Simplified Chinese doesn't suffer the same problem with Traditional Chinese.

**Comment by moonlight-pz** [comment]
> Never mind the last comment, it seems like Simplified Chinese doesn't suffer the same problem with Traditional Chinese.

Thanks for the reminder, due to previous small mistakes, the simplified Chinese translation uses English punctuation. No errors have been found for the time being.

**Comment by mrazgrass** [comment]
In /Muldraugh, KY/description.txt:

> 马尔德劳是诺克斯郡的一个小镇，位于肯塔基州中心地带。

The original:

> Muldraugh is a small town in an area the locals know as "Knox Country" - the dead centre of the State of Kentucky.

The original description suggests "Knox Country" is at the dead centre of Kentucky, not Muldraugh, as your translation would be suggesting.

Muldraugh is within Knox Country, which means inherently, sure, it wouldn't be wrong to say it's also in the dead centre of Kentucky, but that isn't what the original trying to convey.

In other words, "the dead centre of the State of Kentucky" is describing Knox Country, rather than Mauldraugh, even though the statement would be true either way, the authenticity of the translation would be appreciated.

It's just a subtle mistake I've noticed while going through your updates trying to improve mine, my intention is not to be some kind of police on your works, I hope you understand.

**Comment by moonlight-pz** [comment]
> In /Muldraugh, KY/description.txt:
> 
> > 马尔德劳是诺克斯郡的一个小镇，位于肯塔基州中心地带。
> 
> The original:
> 
> > Muldraugh is a small town in an area the locals know as "Knox Country" - the dead centre of the State of Kentucky.
> 
> The original description suggests "Knox Country" is at the dead centre of Kentucky, not Muldraugh.
> 
> Muldraugh is within Knox Country, which means inherently, sure, it wouldn't be wrong to say it's also at the centre of Kentucky, but that isn't what the original trying to convey.
> 
> In other words, "the dead centre of the State of Kentucky" is describing Knox Country, rather than Mauldraugh. Even though the statement would be true either way, the authenticity of the translation would be appreciated.
> 
> It's just a subtle mistake I've noticed while going through your updates trying to improve mine, my intention is not to be some kind of police on your works, I hope you understand.

Take it easy, you are right. communication will make things better.thank you.

**Comment by ProjectSky** [comment]
> https://github.com/TheIndieStone/ProjectZomboidTranslations/blob/62a3434ff580c51bddec99ebe7d3bb9082219d53/CN/Moveables_CN.txt#L562
* ```Standing Vault``` 正确的翻译为立式保险柜

**Comment by moonlight-pz** [comment]
> > https://github.com/TheIndieStone/ProjectZomboidTranslations/blob/62a3434ff580c51bddec99ebe7d3bb9082219d53/CN/Moveables_CN.txt#L562
> 
> * `Standing Vault` 正确的翻译为立式保险柜

感谢反馈，已经更改为立式保险柜

**Pull request merged**
