### PR TITLE
Update ItemName_DE.txt

### PR DESCRIPTION
**Pull request by Hammerbund**

### CODE REVIEW

**Comment by nsKpz** [comment]
Your ItemName_DE.txt is encoded in UTF-8.
If you change it to ANSI or Windows 1252 it will stay compatible with the game and it won't detect every line with an Umlaut as a change.

Regarding the name change, I generally agree that the name could change, though _Lötkolben_ usually refers to a soldering iron instead of a blow torch. 
Would you think _Schneidbrenner_ fits better in the context the item is used in the game?

**Comment by Faalagorn** [comment]
It would be nice if #155 be addressed somehow, it would make editing other languages through GitHub much easier and open up for other possibilities in future (more languages, glyphs, fonts etc.)

**Comment by Hammerbund** [comment]
No, my ItemName_DE.txt  is encoded in ANSI.

**Comment by Hammerbund** [comment]
image

In 3 Dateien habe ich jeweils nur Propanfackel zu Schneidbrenner geändert.
Bei der Recipes.de.txt wird es richtig angezeigt. Also das ich nur diese eine Zeile geändert habe.
Bei den anderen beiden Dateien sind wieder X Sachen dabei, die ich nicht verändert habe...

Alle Dateien sind in ANSI. Was läuft da falsch?

**Pull request merged**
