### PR TITLE
Polish IWBUMS 40.9 update

### PR DESCRIPTION
**Pull request by geras-PL**

### CODE REVIEW

**Comment by geras-PL** [comment]
Hey, I don't know what conflict that is in Items_PL. Please help xd Thanks.

**Comment by Connall** [comment]
Did you copy and paste from another file in to PL/Items_PL.txt because it looks like it's flagging up everything as being conflicted in there.

**Comment by geras-PL** [comment]
Hey, I don't remember doing anything like that. Is there anything I can do to fix the conflict?

**Comment by Connall** [comment]
Maybe some sort of encoding change. I'm honestly not sure what the issue is, maybe try grabbing a clean version of the branch and translating it again. I'm not sure.

**Comment by geras-PL** [comment]
Can you delete this pull request? I'll try to create a new one, we'll see if this sorts out this conflict.

**Comment by geras-PL** [comment]
Because everything works fine in-game on my end anyway.

**Pull request closed without merging**
