### PR TITLE
EN: Updated game options entries to title case

### PR DESCRIPTION
**Pull request by Faalagorn**
Most of the options in "OPTIONS" menu were in title case, so I updated rest to match. Most were in UI_EN, but some are in IG_UI_EN
While at it, added colons to controller options and unified "double tapping" tooltip.

### CODE REVIEW

**Comment by Faalagorn** [comment]
I just rebased this to include my latest changes. Any feedback on this? It basically unifies the option casing plus some minor changes. Some sentences are indeed long, but I tried to keep them uniform.

**Comment by nsKpz** [comment]
Went through them with Will again. 
Sentences not getting capitalized, etc. Closing.

**Comment by Faalagorn** [comment]
> Went through them with Will again.
> Sentences not getting capitalized, etc. Closing.

You both must have enough of me :D Thanks for taking care of it though!

**Comment by nsKpz** [comment]
Ha, not at all! <3

Keep 'em coming.

**Pull request closed without merging**
