### PR TITLE
Updated CN credits

### PR DESCRIPTION
**Pull request by Mishasama**
Make the sorting correct to respect our 'old' leader. (Only add the news, not change the olds.)

These changes should be no harm to anyone.🙌

### CODE REVIEW

**Comment by nsKpz** [comment]
Make the sorting alphabetical?
Not sure why it needs to be sorted chronologically at all.

**Comment by Mishasama** [comment]
> Make the sorting alphabetical if you guys can't agree on the order of the credits?
> 
> Or describe who made the old translations and who's doing the new ones now, similar to how the korean translation does it?:
> https://github.com/TheIndieStone/ProjectZomboidTranslations/blob/master/KO/credits.txt
> 
> Not sure why it needs to be one or the other. I'd really like if the drama would stop spilling into the translation.

The reason is simple. Because the new team is making some unnecessary changes, just to make it look different from the olds to show their revolutionary determination. And they won't agree with the old goals. They want to win the whole war.
In this case, we (the old team) can't provide any support for that cause it's not and can't be maintained by us - they never accept anything from us. We just want to peace and stay in a friendly atmosphere to enjoy our game time, and we don't have so much time like kids to play their endless 'drama' game.
So we should ensure that the players will not be confused. They should ask the new team for that, not the old.

Or if you still want to use us to polish out more precise translations to make your game look more professional. While letting them keep contributing to make this drama goes to a good ending. You should persuade them to join our repository sincerely. We always welcome contributors without hatred and will treat every improvement proposal equally.

@nsKpz man serious, I don't like this too. But if we have no choice, this PR is just like the korean does, I have already marked them as the new team in line 6.

**Comment by nsKpz** [comment]
> The reason is simple. Because the new team is making some unnecessary changes, just to make it look different from the olds to show their revolutionary determination. And they won't agree with the old goals.

I think that's reading a bit much into the whole thing. Starting an argument about a trivial thing like this and then implying you want them to remove everything you've personally translated just to re-translate it is also a bit petty. 

This is a situation I cannot properly judge because it largely takes place in a language I do not speak nor understand. Nor can I judge the quality of the translation, properly.
All I have to go by are conflicting statements from two opposing parties that would be better off working together in order to get the Chinese translation in order, and let their bygones be bygones instead of throwing accusations at each other.

> But if we have no choice, this PR is just like the korean does, I have already marked them as the new team in line 6.

I'd say make that a bit clearer and explicitly state so instead of relying on the mere implication of the top lines being old translators. People cannot tell without context.

**Comment by Mishasama** [comment]
> Edit: Sorry if this comes across as impolite, that's not my intention. I'm immensely thankful for your contribution over the years.

@nsKpz 
Dude, never mind, I get your temperament.

Feel me a bit petty? Please let me tell you more.
For example, they change the "Police Shirt" to "Police's Shirt" in translation, then telling people your translation is very bad, and they already change it to their better ORIGINAL translation.

Our old team already has a roadmap for a clear division of labor and built a feedback and contribution system.
I also made some community events to encourage people to join us and encourage the community to become active.
But what they do? Jealous of what I've done and stealing them all from me and then slander me?

How would you feel?

I feel they are not just thieves, take your work and claim they own it. They also slander you and discredit your work. While making things to be worse.

I can let their bygones be bygones, but what about them?


I have changed the content according to your request. https://github.com/Mishasama/ProjectZomboidTranslations/blob/master/CN/credits.txt
Maybe this is the last thing that I can do for the old team. I'm sorry to upset you.

**Comment by nsKpz** [comment]
I don't feel comfortable with that change either, since it reads quite passive aggressive and I feel instead of de-escalating the situation it would contribute to further escalation.
While I am thankful for your contributions, I am really starting to run low on patience on this. 
Please make sure that the next update is a new PR and does not fuel the drama fire even more.

**Pull request closed without merging**
