### PR TITLE
Update for 41.40

### LINKED ISSUE #336: UI_CN.txt
@Mishasama 

Please edit these lines and remove the references to sites that are not our forums.

UI_ModsNagPanel_Title =
UI_ModsNagPanel_Text =

### PR DESCRIPTION
**Pull request by Mishasama**
+ Add cars translate
+ New translations for Moveables
* Partial polish Stash Mishasama/ProjectZomboidTranslations#48 & Moveables
* Lot of other polishes
* Resolved #336
- Empty Items_CN.txt to upgrade to ItemName_CN.txt

### CODE REVIEW

**Review by nsKpz — CHANGES_REQUESTED** [review]
Please remove any remaining mentions of sites or groups that are not officially part of The Indie Stone. 
This includes bilibili links and remaining QQ referals.

Specifically UI_News_Anim still refers to the QQ group. 

Remove anything that makes a community translation project appear as official, or that implies we're looking for chinese team membes. 
You *can* put an emphasis on encouraging chinese translators to help out with the project by linking to Github and/or our forums, but nothing outside of our official forums or online platforms .

**Comment by Mishasama** [comment]
> Please remove any remaining mentions of sites or groups that are not officially part of The Indie Stone.
> This includes bilibili links and remaining QQ referals.
> A link to your translations of the changelogs can remain if you make it obvious they're a community effort and not official.
> 
> Specifically UI_News_Anim still refers to the QQ group.
> 
> Remove anything that makes a community translation project appear as official, or that implies we're looking for chinese team membes.
> You _can_ put an emphasis on encouraging chinese translators to help out with the translation by linking to Github and/or our forums, but nothing outside of our official forums or online platforms .

There is a problem for people who live in China Mainland, they can't access Github or even steam community freely because of government policy.
And almost players can't read or write English smoothly for report bugs, they want a place and someone can translate that then send it to TIS.

Even so, I still respect your decision.

**Comment by nsKpz** [comment]
Good point, I didn't think of that. We'll think of something and I'll get back to you as soon as possible.

**Comment by nsKpz** [comment]
Alright, so you can leave a reference to the Q Group / bilibili changelog in there, if you add the following text right next to it (translated):

> Community Translator note: THIS SITE IS NOT AFFILIATED WITH THE INDIE STONE. THE DEVELOPERS OF PROJECT ZOMBOID ARE NOT RESPONSIBLE FOR ANYTHING ON THIS WEBSITE.

This is because we were notified that there is a paid package called "Project Zomboid Official Chinese" that is being sold in that group. Needless to say that if you have the influence to do so, we also ask you to remove the paywall as well as removing the implication that it's official with both the installation package as well as the Q Group and - if existant - the bilibili pages.

**Comment by Mishasama** [comment]
> Alright, so you can leave a reference to the Q Group / bilibili changelog in there, if you add the following text right next to it (translated):
> 
> > Community Translator note: THIS SITE IS NOT AFFILIATED WITH THE INDIE STONE. THE DEVELOPERS OF PROJECT ZOMBOID ARE NOT RESPONSIBLE FOR ANYTHING ON THIS WEBSITE.
> 
> This is because we were notified that there is a paid package called "Project Zomboid Official Chinese" that is being sold in that group. Needless to say that if you have the influence to do so, we also ask you to remove the paywall as well as removing the implication that it's official with both the installation package as well as the Q Group and - if existant - the bilibili pages.

Sorry for the confusion, the Q Group has been removed from UI because the paywall is the credit card like verification system, and it won't be removed. But that can be refunded if that isn't a spam account. This can make sure the group keeps away from the spam or bot accounts. And all about this was written at the group introduction.

Attention, we were NEVER SOLD ANY PACKAGE, the package is completely free for the trusted users, and it ONLY for tests used, because we have to make sure the bad quality or any obvious bug won't be spare around.
Meantime, we noticed that there were some people annoyed by the paywall because they NEVER pay attention to the introduction and was yelled at the group (we have records and witnesses), but we think these people won't be friendly for the community, so we decided to keep this, for the community health.

**Comment by nsKpz** [comment]
Thanks for letting us know, and for your continuous work on the translations <3

**Pull request merged**
