### PR TITLE
Remade News_cn.txt and optimize words and add missing translations

### PR DESCRIPTION
**Pull request by moonlight-pz**
News_cn.txt has been remade, so players can know more clearly what changes are made in 41.40-41.50.

The name of the bottle has been changed and it now looks more orderly.

Some words have been changed, now they are more intuitive

According to what you mean, we sorted them alphabetically. And divided into two groups.

Added missing translation:

    Recipe_Advanced_Mechanics = "莱恩斯汽车手册-性能车型",
    Recipe_Basic_Mechanics = "莱恩斯汽车手册-标准车型",
    Recipe_Intermediate_Mechanics = "莱恩斯汽车手册-商用车型",
    Pinewood_Floor = "松木地板",
    Corner_B_Shelves = "矮货架（右）",
    Corner_A_Shelves = "矮货架（左）",
    Middle_Shelves = "矮货架（中）",
    Oak_Left_Bar = "酒吧橡木货架（左）",
    Oak_Middle_Bar = "酒吧橡木货架（中）",
    Oak_Right_Bar = "酒吧橡木货架（右）",
    Sandbox_ZCrawlUnderVehicle = "爬过车底",
    Sandbox_ZCrawlUnderVehicle_option1 = "从不",
    Sandbox_ZCrawlUnderVehicle_option2 = "非常少",
    Sandbox_ZCrawlUnderVehicle_option3 = "稀少",
    Sandbox_ZCrawlUnderVehicle_option4 = "有时",
    Sandbox_ZCrawlUnderVehicle_option5 = "经常",
    Sandbox_ZCrawlUnderVehicle_option6 = "非常多",
    Sandbox_ZCrawlUnderVehicle_option7 = "全部",

### CODE REVIEW

**Review by Mishasama — CHANGES_REQUESTED** [review]
FU, you mess up the file again :)
Why you can't keep your works clean? Don't make your hands dirty, okay?

**Comment by moonlight-pz** [comment]
> FU, you mess up the file again :)
> Why you can't keep your works clean? Don't make your hands dirty, okay?

FU2! Why should you use the Japanese system to view simplified Chinese? Do you know that the encoding of simplified Chinese is UTF-8? Please use the simplified Chinese system to participate in the production of simplified Chinese

**Comment by moonlight-pz** [comment]
> FU, you mess up the file again :)
> Why you can't keep your works clean? Don't make your hands dirty, okay?

Yes, first of all I apologize for the previous impulse. Credits.txt is indeed a problem, I have now corrected it. But I don't like your tone, especially when you impose the unpleasantness of the past on me.

**Comment by Mishasama** [comment]
> > FU, you mess up the file again :)
> > Why you can't keep your works clean? Don't make your hands dirty, okay?
> 
> Yes, first of all I apologize for the previous impulse. Credits.txt is indeed a problem, I have now corrected it. But I don't like your tone, especially when you impose the unpleasantness of the past on me.

I just want to said can you fix the conflicts yourself? Don't bother nsKpz or others to take that works for you every time.


Oh, about the credits. Just keep it untouched, or only modify your team's lines, don't touch us okay? Or you need me to say it in Chinese for you?

**Comment by nsKpz** [comment]
> > > FU, you mess up the file again :)
> > > Why you can't keep your works clean? Don't make your hands dirty, okay?
> > 
> > 
> > Yes, first of all I apologize for the previous impulse. Credits.txt is indeed a problem, I have now corrected it. But I don't like your tone, especially when you impose the unpleasantness of the past on me.
> 
> I just want to said can you fix the conflicts yourself? Don't bother nsKpz or others to take that work for you every time.
> 
> Oh, about the credits. Just keep it untouched, or only modify your team's lines, don't touch us okay? Or you need me to say it in Chinese for you?

They had the maturity to edit their post.

It's disappointing to see that you on the other hand continue to show open disdain and act immaturely, making this a toxic environment.
I do not want this kind of toxicity anywhere near me nor anyone contributing here. You're better of not contributing if you can't drop it.

**Comment by Mishasama** [comment]
> > > > FU, you mess up the file again :)
> > > > Why you can't keep your works clean? Don't make your hands dirty, okay?
> > > 
> > > 
> > > Yes, first of all I apologize for the previous impulse. Credits.txt is indeed a problem, I have now corrected it. But I don't like your tone, especially when you impose the unpleasantness of the past on me.
> > 
> > 
> > I just want to said can you fix the conflicts yourself? Don't bother nsKpz or others to take that work for you every time.
> > Oh, about the credits. Just keep it untouched, or only modify your team's lines, don't touch us okay? Or you need me to say it in Chinese for you?
> 
> They had the maturity to at least edit their post.
> 
> It's disappointing to see that you on the other hand continue to show open disdain and act immaturely, making this a toxic environment.
> I do not want this kind of toxicity anywhere near me nor anyone contributing here. You're better of not contributing if you can't drop it and be an adult. You're stopping down to a level that you've condemned them for.
> 
> I understand you not wanting to work with them after all the accusations and false accusations from that side of the translation team, but do not come here and insult them for mistakes.

I don't know why do they keep editing credits about our team after the last time you had updated it?
That's not something that they should touch again and again. This is a matter of principle.
I don't have any more demands, just this one, if you don't care they mess up other things.

If I say nothing here, then they will succeed to edit the credits to what they want again without us noticed.
Or you really agree with them to keep disdain us? That's not just a mistake. They are deliberately drowning it in this mass of changes to submit in order to hide it from us.

**Comment by moonlight-pz** [comment]
> > > > > FU, you mess up the file again :)
> > > > > Why you can't keep your works clean? Don't make your hands dirty, okay?
> > > > 
> > > > 
> > > > Yes, first of all I apologize for the previous impulse. Credits.txt is indeed a problem, I have now corrected it. But I don't like your tone, especially when you impose the unpleasantness of the past on me.
> > > 
> > > 
> > > I just want to said can you fix the conflicts yourself? Don't bother nsKpz or others to take that work for you every time.
> > > Oh, about the credits. Just keep it untouched, or only modify your team's lines, don't touch us okay? Or you need me to say it in Chinese for you?
> > 
> > 
> > They had the maturity to at least edit their post.
> > It's disappointing to see that you on the other hand continue to show open disdain and act immaturely, making this a toxic environment.
> > I do not want this kind of toxicity anywhere near me nor anyone contributing here. You're better of not contributing if you can't drop it and be an adult. You're stopping down to a level that you've condemned them for.
> > I understand you not wanting to work with them after all the accusations and false accusations from that side of the translation team, but do not come here and insult them for mistakes.
> 
> I don't know why do they keep editing credits about our team after the last time you had updated it?
> That's not something that they should touch again and again. This is a matter of principle.
> I don't have any more demands, just this one, if you don't care they mess up other things.
> 
> If I say nothing here, then they will succeed to edit the credits to what they want again without us noticed.
> Or you really agree with them to keep disdain us? That's not just a mistake. They are deliberately drowning it in this mass of changes to submit in order to hide it from us.

We did not hide the changes to credits.txt, I have written them in the update log. We strictly follow this [418](https://github.com/TheIndieStone/ProjectZomboidTranslations/pull/418). Alphabetical sorting is a great idea to prevent other quarrels about who is first and second.
Just like the respect we expressed to you, we should also make any contributors feel respected.
I am puzzled why you want to prevent things from going better

Warning: Just one is enough. It would be a disaster to reappear similar people.. Or we choose to delete your name and my name in credits.txt to end the quarrel. Make the environment better. Since the establishment of the new Chinese translation group, you only care about credits.txt, which is puzzling. Maybe our work has been done so well that you can only laugh at us like this. I don't want to express a worse attitude to you.So i won't reply to you again.

**Comment by Mishasama** [comment]
> We did not hide the changes to credits.txt, I have written them in the update log. We strictly follow this [418](https://github.com/TheIndieStone/ProjectZomboidTranslations/pull/418). Alphabetical sorting is a great idea to prevent other quarrels about who is first and second.
> Just like the respect we expressed to you, we should also make any contributors feel respected.
> I am puzzled why you want to prevent things from going better

Oh, really? Where is your log? I can't find it here. Can you show me, please?

> Warning: Just one is enough. It would be a disaster to reappear similar people.. Or we choose to delete your name and my name in credits.txt to end the quarrel. Make the environment better. Since the establishment of the new Chinese translation group, you only care about credits.txt, which is puzzling. Maybe our work has been done so well that you can only laugh at us like this. I don't want to express a worse attitude to you.So i won't reply to you again.

https://github.com/TheIndieStone/ProjectZomboidTranslations/commit/26ec9cea9299f33d32f0dfae8dd0960313882387
You can't see that? Why do you use your old version again? Yeh, you guys just want to wipe me out huh?
I only care about this file? When you think you are better, I don't think I can do anything for these anymore when the TIS can't judge between us. That will ONLY make the process down forever. So, please go on. I won't ban your translations like what you do on me.

BUT I WON'T LET YOU HURT OUR TEAM!

**Comment by nsKpz** [comment]
Order of first team just won't be changed. 

The end.

**Comment by moonlight-pz** [comment]
> Order of first team just won't be changed.
> 
> The end.

It has been modified according to your requirements.

**Comment by nsKpz** [comment]
Merged this, with a slightly modified credits file.

Just want you to be a ware that Chinese letters aren't displayed properly in the options screen. Was this working before?

**Comment by moonlight-pz** [comment]
> Merged this, with a slightly modified credits file.
> 
> Just want you to be a ware that Chinese letters aren't displayed properly in the options screen. Was this working before?

Thank you for your modification, I also saw that you helped me transcode.

It was correct before and I will fix it. Then submit it to you. It uses GB2312 encoding.

**Pull request closed without merging**
